const mongoose=require('mongoose')
const userSchema=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        unique:true
    },
    name:{
        type:String,
        required:true
    },
    lastname:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    address:{
        type:String,
        required:true
    },
    companyName:{
        type:String,
        required:true
    },
    logo:{
        type:String
    },
    password:{
        type:String,
        required:true
    }
})
module.exports=mongoose.model("userdata",userSchema)